services:
  postgres:
    container_name: postgres
    image: postgres:bullseye
    env_file: "./.env"
    environment:
      PGDATA: /var/lib/postgresql/rust_data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - rust_data:/var/lib/postgresql/rust_data/pgdata
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  rust_data:
